### ISSUE TITLE
Implement parallel processing in inclusivelint

### ISSUE THREAD

**Issue by squassina** [inclusivelint/inclusivelint#32]
implement something simple as documented here:
https://www.cyberciti.biz/faq/how-to-run-command-or-code-in-parallel-in-bash-shell-under-linux-or-unix/

**Comment by squassina** [comment]
Assigned to myself

**Comment by Guilhermeslucas** [comment]
Ill be closing this since we will be focusing efforts on migrating this to use the typescript library!
