### ISSUE TITLE
Word ignore list?

### ISSUE THREAD

**Issue by AvinZarlez** [inclusivelint/inclusivelint#5]
Might be a useful feature to have a per project ignore list.

Example, I ran it on my project, and I got a lot of warnings for the word "ADD" - All of which was in the context of addition "Add this file to this folder" not implying the medical diagnosis A.D.D.

It may or may not make sense to remove the check for the word "ADD", I wouldn't want to skip over recommending people do not use it in the diagnosis context. I suspect I might not be only one who can confirm I am only using it in the addition context, and I can safely ignore the warning.

**Comment by Guilhermeslucas** [comment]
Loved the suggestion @TobiahZ 
I started thinking about this feature and I can see some paths to achieve that, and I wanted to hear your thoughts on what is the one the be chosen:

- Right now we have the dictionary of words as a text file. Should we edit that?
- Should we have a .inclusivelintignore file somewhere, that tells what are the words that are allowed?
- Should we have a command that adds ignored words, and them its up to us how to implement that?

What do you think?
CC: @fernandoBRS

**Comment by AvinZarlez** [comment]
1. I'd vote keep the word. "Add" is definitely going to trigger A LOT of false positives. But so are a ton of other words on the list though, so I'm ok, especially as a warning, to get those errors at least on a first run. The intent of this is not to always get to zero warnings, but check language use and find parts that could be phrased better.

1. I think an ignore file is the most practical way to handle this. That way it can also be referenced on a per project basis when being ran as part of a cloud build.

1. A command that generates / adds words to / removes words from the ignore list may be very useful. Especially when it comes to adding/removing words that have multiple triggers (ex: "Doorman" and "Doorwomen") where it's not clear to the user what the ID is (ex: "doorman-doorwoman")

**Comment by fedeoliv** [comment]
I like the `.inclusivelintignore` approach as it brings more flexibility to any project. As we've seen, a lot of false positives occurs and that's ok, each project can adapt to their needs.

**Comment by Guilhermeslucas** [comment]
Nice! Ill follow this approach then! Thanks!
