### ISSUE TITLE
Why is Bi on the list?

### ISSUE THREAD

**Issue by AvinZarlez** [inclusivelint/inclusivelint#6]
Came up in a project of mine I ran this on.

I'm not sure why Bi is listed as a warning word?

I have never heard of bisexual being preferred over bi? I know a lot of bisexual people (including myself kinda, though I identify more with pansexual these days) and I've never heard of it being in any way problematic.

Not to mention it seemed to give warnings on false positives like binary.

**Comment by Guilhermeslucas** [comment]
Hello @TobiahZ , thanks for openning this issue! We are getting the words from the [retext equality database](https://github.com/retextjs/retext-equality/blob/main/rules.md), so I would say there is no special reason haha Loved your explanation and I am oppening a PR to fix this!
